/**
 * Orval custom mutator (fetch client).
 *
 * Every function generated by Orval is routed through `customInstance`.
 * Orval's fetch client invokes it as:
 *
 *   customInstance<ResponseUnion>(url, requestInit)
 *
 * where `requestInit.body` is already JSON-serialized and `requestInit.method`
 * is uppercase ("GET", "POST", ...). The expected return shape is the
 * discriminated union Orval generates per route:
 *
 *   { status: number; data: T; headers: Headers }
 *
 * We adapt that to the existing `@aglaya/api-core` ApiClient so all auth /
 * envelope / error normalization stays in one place.
 *
 * Do NOT call ApiClient directly from generated code — generated code only
 * knows this mutator.
 */
import type { JSONTypes } from "@aglaya/api-core";

import { apiClient, getAuthToken } from "@/config/api-client";
import { ApplicationError } from "@/utils/errors";

type Method = "get" | "post" | "put" | "patch" | "delete";

const isMethod = (m: string): m is Method =>
  m === "get" || m === "post" || m === "put" || m === "patch" || m === "delete";

/**
 * Strip the baseURL prefix from the absolute path Orval emits. Orval bakes
 * the spec's path ("/api/budgets/{id}/income") directly into the generated
 * URL builder; ApiClient already prepends its own baseURL, so we'd double up.
 * The ApiClient base ends with "/api" → strip the leading "/api" if present.
 */
const stripApiPrefix = (url: string): string =>
  url.startsWith("/api/") ? url.slice(4) : url;

/**
 * Orval pre-serializes JSON bodies. We feed ApiClient an object, not a string —
 * undo the serialization. FormData passes through untouched.
 */
const decodeBody = (body: BodyInit | null | undefined): JSONTypes | FormData | undefined => {
  if (body == null) { return undefined; }
  if (body instanceof FormData) { return body; }
  if (typeof body === "string") {
    try { return JSON.parse(body) as JSONTypes; }
    catch { return body; }
  }
  // Blob/ArrayBuffer/URLSearchParams aren't expected for our API; fall through.
  return undefined;
};

export const customInstance = async <T>(
  url: string,
  init: RequestInit = {},
): Promise<T> => {
  const token  = getAuthToken();
  const method = (init.method ?? "GET").toLowerCase();

  if (!isMethod(method)) {
    throw new ApplicationError(`Unsupported HTTP method: ${init.method}`);
  }

  const path = stripApiPrefix(url);

  const envelope = await apiClient[method]<unknown>(path, {
    headers:         init.headers as Record<string, string> | undefined,
    body:            decodeBody(init.body),
    authentication:  token ? { token } : undefined,
  });

  if (envelope.status !== "ok") {
    throw new ApplicationError(
      `Request failed: ${method.toUpperCase()} ${path}`,
      undefined,
      envelope.statusCode,
    );
  }

  // Reshape into Orval's expected `{ status, data, headers }` union variant.
  // The cast is required because T is a discriminated union per status code,
  // and we don't statically know which arm we're in at the mutator layer.
  return {
    status:  envelope.statusCode ?? 200,
    data:    envelope.response,
    headers: new Headers(envelope.headers ?? {}),
  } as unknown as T;
};

// Helper aliases Orval-generated code sometimes references.
export type ErrorType<Error>   = Error;
export type BodyType<BodyData> = BodyData;

export default customInstance;
